/*
 * Defines.cpp
 *
 *  Created on: Dec 7, 2017
 *      Author: mirime
 */

#include "Defines.h"

#define WAROIDDIRECTIONELSEIFRETURN(e,n)	else if (strcasecmp(#e, n) == 0) return WAROIDDIRECTION::e;
namespace WAROIDDIRECTION
{
	ETYPE getType(GRCCSTR name)
	{
		if (name == nullptr)
			return ETYPE::NONE;

		WAROIDDIRECTIONELSEIFRETURN(FORWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(BACKWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(LEFT, name)
		WAROIDDIRECTIONELSEIFRETURN(RIGHT, name)
		WAROIDDIRECTIONELSEIFRETURN(LEFT_FORWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(RIGHT_FORWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(LEFT_BACKWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(RIGHT_BACKWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(LEFT_TURN, name)
		WAROIDDIRECTIONELSEIFRETURN(RIGHT_TURN, name)

		return ETYPE::NONE;
	}
}

#define WAROIDWEAPONFIREELSEIFRETURN(e,n)	else if (strcasecmp(#e, n) == 0) return WAROIDWEAPONFIRE::e;
namespace WAROIDWEAPONFIRE
{
	ETYPE getType(GRCCSTR name)
	{
		if (name == nullptr)
			return ETYPE::UNKNOWN;

		WAROIDWEAPONFIREELSEIFRETURN(UNKNOWN, name)
		WAROIDWEAPONFIREELSEIFRETURN(GATLING, name)
		WAROIDWEAPONFIREELSEIFRETURN(CANNON, name)

		return ETYPE::UNKNOWN;
	}
}
