/*
 * Defines.cpp
 *
 *  Created on: Dec 7, 2017
 *      Author: mirime
 */

#include "Defines.h"

#define WAROIDDIRECTIONELSEIFRETURN(e,n)	else if (strcasecmp(#e, n) == 0) return WAROIDDIRECTION::e;
namespace WAROIDDIRECTION
{
	ETYPE GetType(GRCCSTR name)
	{
		if (name == nullptr)
			return ETYPE::NONE;

		WAROIDDIRECTIONELSEIFRETURN(FORWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(BACKWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(LEFT, name)
		WAROIDDIRECTIONELSEIFRETURN(RIGHT, name)
		WAROIDDIRECTIONELSEIFRETURN(LEFT_FORWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(RIGHT_FORWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(LEFT_BACKWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(RIGHT_BACKWARD, name)
		WAROIDDIRECTIONELSEIFRETURN(LEFT_TURN, name)
		WAROIDDIRECTIONELSEIFRETURN(RIGHT_TURN, name)

		return ETYPE::NONE;
	}
}

#define WAROIDWEAPONELSEIFRETURN(e,n)	else if (strcasecmp(#e, n) == 0) return WAROIDWEAPON::e;
namespace WAROIDWEAPON
{
	ETYPE GetType(GRCCSTR name)
	{
		if (name == nullptr)
			return ETYPE::UNKNOWN;

		WAROIDWEAPONELSEIFRETURN(UNKNOWN, name)
		WAROIDWEAPONELSEIFRETURN(GATLING, name)
		WAROIDWEAPONELSEIFRETURN(CANNON, name)
		WAROIDWEAPONELSEIFRETURN(LASER, name)

		return ETYPE::UNKNOWN;
	}
}
